In [15]:
import numpy as np

In [17]:
i_1 = [1,10,100,1000] # Individuum 1-5
i_2 = [2,20,200,2000]
i_3 = [3,30,300,3000]
i_4 = [4,40,400,4000]
i_5 = [5,50,500,5000]

population = np.array([i_1, i_2, i_3, i_4, i_5])
eigenschaftsraum = np.transpose(population)
                
for eig in eigenschaftsraum:
    np.random.shuffle(eig)

population = np.transpose(eigenschaftsraum)

print population


[[   2   40  500 5000]
 [   1   50  200 1000]
 [   4   10  300 3000]
 [   3   30  100 2000]
 [   5   20  400 4000]]
